#!/bin/bash
#SBATCH --job-name=ppM10J4B4P1N1024  # create a short name for your job
#SBATCH --nodes=1                  # node count
#SBATCH --ntasks=1                 # total number of tasks across all nodes
#SBATCH --cpus-per-task=36         # cpu-cores per task (>1 if multi-threaded tasks)
#SBATCH --partition=bigmem
#SBATCH --mail-type=end,fail
#SBATCH --mail-user=sanghyuk.moon@princeton.edu
#SBATCH --mem-per-cpu=80G               # memory per node
#SBATCH --time=12:00:00          # total run time limit (HH:MM:SS)

######SBATCH --mem=2880G               # memory per node

module purge
module load anaconda3/2022.5
conda activate pyathena

# === Edit here ============
TASK="--run-grid"
#TASK="--prune"
#TASK="--track-cores -o"
#TASK="--track-protostellar-cores -o"
#TASK="--radial-profile"
#TASK="--critical-tes -o"
#TASK="--lagrangian-props -o"
#TASK="--projections -o"
#TASK="--prj-radial-profile -o"
#TASK="--observables -o"
#TASK="--linewidth-size -o"
#TASK="--plot-core-evolution -o"
#TASK="--plot-sink-history"
MODEL=${SLURM_JOB_NAME#pp}
# ==========================

# single jobs
cmd="--unbuffered python do_tasks.py $MODEL $TASK --np $SLURM_CPUS_PER_TASK"

# Multiple models
#MODELS=$(echo M5J2P{30..39}N512)
#MODELS=$(echo M10J4P{0..6}N1024)
#cmd="--unbuffered python do_tasks.py $MODELS $TASK --np $SLURM_CPUS_PER_TASK"

echo $cmd
srun $cmd

# Notes on memory usage
# ---------------------
# grid-denro
# 1024 ~ 80 GB per core
# 512  ~ 10 GB per core
#
# core tracking
# 1024 ~ 14 GB per core
# 512 ~ 0.8 GB per core

# radial profile
# 1024 ~ 170 GB per core (exactly, max(mem) = 163.8 GB for test run as of 241218)
# 512 ~ 21 GB per core (needs to be updated)
# 256 ~ 3.1 GB per core

# critical core
# 1024 ~ 
# 512 ~ 35 MB

# projections
# 1024 ~ 90 GB per core
# 512 ~ 10 GB per core

# prj_radial_profile
# 220 MB per core (negligible)

# observables
# 1024 ~ 15 GB per core

# Core evolution plot
# 1024 ~ 30 GB per core
# 512 ~ 3 GB per core

# linewidth-size
# 1024 ~ 77 GB per core (106 GB per core for critical cores)
# 512  ~ 9 GB per core
