#!/bin/bash
#SBATCH --job-name=ppPRFM        # create a short name for your job
#SBATCH --nodes=1                  # node count
#SBATCH --ntasks=1                 # total number of tasks across all nodes
#SBATCH --cpus-per-task=20          # cpu-cores per task (>1 if multi-threaded tasks)
##SBATCH --partition=bigmem
#SBATCH --mail-type=end,fail
#SBATCH --mail-user=sanghyuk.moon@princeton.edu
#SBATCH --mem-per-cpu=80G               # memory per node
#SBATCH --time=02:00:00          # total run time limit (HH:MM:SS)
#SBATCH --array=0-3


module purge
module load anaconda3/2022.5
conda activate pyathena

#MODEL=${SLURM_JOB_NAME#pp}
#
## === Edit here ============
#TASK="--plot-core-evolution"
#MODEL=${MODEL%pce}
#PID_START=46
#PAR_PER_TASK=10
## ==========================
#
#PS=$((PID_START+PAR_PER_TASK*SLURM_ARRAY_TASK_ID))
#PE=$((PS+PAR_PER_TASK-1))
#cmd="--unbuffered python do_tasks.py $MODEL $TASK --np $SLURM_CPUS_PER_TASK --pid-start $PS --pid-end $PE"
#echo $cmd
#srun $cmd

# Array over model
cmd="--unbuffered python do_tasks.py L${SLURM_ARRAY_TASK_ID} --prfm -o --np $SLURM_CPUS_PER_TASK"
echo $cmd
srun $cmd
